### ISSUE TITLE
6.3.1 Debounce翻譯問題

### ISSUE THREAD

**Issue by jaychang0917** [mcxiaoke/RxDocs#22]
官方的原文`only emit an item from an Observable if a particular timespan has passed without it emitting another item`. 我覺得應該翻譯為`僅在過了一段指定的時間才發射一個數據而不發射期間的數據`。

從下面的diagram可以看出並不是`仅在过了一段指定的时间还没发射数据时才发射一个数据`的意思。
![image](https://cloud.githubusercontent.com/assets/5347535/15455027/a2b16ea6-207a-11e6-844d-172520491688.png)

**Comment by mcxiaoke** [comment]
欢迎提PR
