### ISSUE TITLE
RexactiveX中文文档修改意见

### ISSUE THREAD

**Issue by jiefly** [mcxiaoke/RxDocs#25]
6.8节==>其他聚合操作符==>reduce( ) — 对序列使用reduce()函数并发射对吼的结果

其中“并发送对吼结果” 这句是否有问题？ 是不是应该改为“发射最终的结果”

**Comment by mcxiaoke** [comment]
可以在线直接修改，欢迎提PR

**Comment by mcxiaoke** [comment]
merged
