### ISSUE TITLE
首先感谢,大家的翻译,

### ISSUE THREAD

**Issue by qiubiteme** [mcxiaoke/RxDocs#36]
不知道,大家考虑到,没有,文中对于方法使用 <操作符>来描述,对于,新接触的人来说,一时之间有点难以绕过弯,建议把操作符换成,方法,这样不是更容易理解吗!还有如何加入,这个翻译组,

**Comment by jp1017** [comment]
还是不要换, 毕竟不是一个东西，在一个领域，用大家通用的语言比较好沟通。
