### ISSUE TITLE
请求转载

### ISSUE THREAD

**Issue by chpengzh** [mcxiaoke/RxDocs#40]
我们建立了一个新的社区[Kotlin China](https://kotlin-cn.org)，请问能否让我们以精品专题形式，转载该项目下的文章。我们将标明原项目地址和作者和项目贡献者，同时期待您的加入。该[项目地址](https://github.com/Kotlin-lang-CN/Kotlin-CN)， 服务使用kotlin编写构建

**Comment by chpengzh** [comment]
该[项目地址](https://github.com/Kotlin-lang-CN/Kotlin-CN)， 服务使用kotlin编写构建

**Comment by mcxiaoke** [comment]
可以，需要注明来源和链接
