### ISSUE TITLE
RxJAVA 使用示例 错别字

### ISSUE THREAD

**Issue by WallenHan** [mcxiaoke/RxDocs#41]
大概位置在 文末请看插图
![image](https://user-images.githubusercontent.com/5639544/28362589-7dda11f0-6caf-11e7-88c2-fdf27be511de.png)

应该为 “这一页“ 或者 “这一章节“ 的， 比较好吧

**Comment by mcxiaoke** [comment]
可以直接在线修改，欢迎提PR

**Comment by mcxiaoke** [comment]
fixed
