### ISSUE TITLE
这里有一个参数描述错误

### ISSUE THREAD

**Issue by docwei2050** [mcxiaoke/RxDocs#44]
doOnEach 操作符让你可以注册一个回调，它产生的Observable每发射一项数据就会调用它一
次。你可以以 Action 的形式传递参数给它，这个Action接受一个 onNext 的变
体 Notification 作为它的唯一参数，**你也可以传递一个Observable给 doOnEach ，这个
Observable的 onNext 会被调用，就好像它订阅了原始的Observable一样。**
Javadoc: doOnEach(Action1))
Javadoc: doOnEach(Observer))
------------
你也可以传递一个**Observer**给 doOnEach,,,  这样才对啊，大神，印刷错误

**Comment by mcxiaoke** [comment]
可以在线修改的，欢迎提PR
