### ISSUE TITLE
doOnSubscribe  doOnUnsubscribe 描述错误

### ISSUE THREAD

**Issue by docwei2050** [mcxiaoke/RxDocs#45]
doOnUnsubscribe 操作符注册一个动作，当观察者取消订阅它生成的Observable它就会被调
用。
doOnSubscribe 操作符注册一个动作，当观察者订阅它生成的Observable它就会被调用。
描述错误啊。。
正常：
doOnUnsubscribe 操作符注册一个动作，当观察者取消订阅Observable，它就会被调
用。
doOnSubscribe 操作符注册一个动作，当观察者订阅Observable，它就会被调用。

**Comment by mcxiaoke** [comment]
可以在线修改的，欢迎提PR
