### ISSUE TITLE
翻译错误

### ISSUE THREAD

**Issue by LuodiJackShen** [mcxiaoke/RxDocs#48]
官方文档原文：
> takeWhile( ) and takeWhileWithIndex( ) — emit items emitted by an Observable as long as a specified condition is true, then skip the remainder

文章当中的翻译：

> takeWhile( ) and takeWhileWithIndex( ) — 发射原始Observable的数据，直到一个特定的条件为真，然后跳过剩余的数据

我认为应该翻译成-发射原始Observable的数据，只要这个条件为真，如果这个条件为假，那就跳过它及它之后剩余的数据。这里的 'as long as'是'只要'的意思，而不是'直到'。

测试代码：

`Observable.just(1, 2, 3, 4, 5)
                .takeWhile(number -> number != 3)
                .subscribe(number -> System.out.println(number));`
输出：
`1
2`

**Comment by mcxiaoke** [comment]
可以直接在线修改提PR
