### ISSUE TITLE
Observables->创建观察者 章节翻译问题

### ISSUE THREAD

**Issue by sunshl** [mcxiaoke/RxDocs#50]
Define a method that does something useful with the return value from the asynchronous call; this method is part of the observer.

目前的翻译为：
定义一个方法，它完成某些任务，然后从异步调用中返回一个值，这个方法是观察者的一部分。

更合理的翻译建议：
定义一个方法，这个方法拿着某个异步调用的返回值做一些有用的事情。这个方法是观察者的一部分。

**Comment by mcxiaoke** [comment]
thanks
